---
title: "GNSS vs. RTK-GNSS Positioning of Forest Inventory Plots"
author: "Florian Franz"
format: html
---

## Indroduction

Global Navigation Satellite Systems (GNSS) are widely used for geolocating terrestrial sample plots in forest inventories. However, the accuracy of GNSS positioning varies due to factors such as the number and positions of satellites, obstacles affecting signal reception, and atmospheric conditions (Johnson & Barton, 2004). In dense forest environments, these effects are particularly pronounced, and positional errors of standard GNSS receivers can reach up to 5–10 m (McRoberts et al., 2018).

Real-Time Kinematic (RTK) GNSS correction significantly reduces these errors by using a fixed reference station or network to provide real-time differential corrections, achieving sub-meter positional accuracy (Pascual et al., 2020).

Precise plot positions are crucial in the context of remote sensing applications in forestry. Wall-to-wall datasets such as airborne laser scanning (ALS), aerial imagery, or satellite-derived canopy metrics are increasingly used to model and predict forest inventory attributes. Misregistration between field plots and remote sensing data directly increases model uncertainty (Frazer et al, 2011, McRoberts et al., 2018).

## Analysis

This analysis compares the positional accuracy of GNSS and RTK-corrected GNSS measurements for terrestrial forest inventory sample plots. By assessing the differences between both positioning methods, the potential improvement in plot coordinate accuracy achieved through RTK correction is quantified, and its implications for the co-registration of field plots with remote sensing data are evaluated.

#### References

Frazer, G.W., Magnussen, S., Wulder, M.A., & Niemann, K.O. (2011). Simulated impact of sample plot size and co-registration error on the accuracy and uncertainty of LiDAR-derived estimates of forest stand biomass. Remote Sensing of Environment, 115(2), 636–649. https://doi.org/10.1016/j.rse.2010.10.008

Johnson, C.E., & Barton, C.C. (2004). Where in the world are my field plots? Using GPS effectively in environmental field studies. Frontiers in Ecology and the Environment, 2(9), 475–482. https://doi.org/10.1890/1540-9295(2004)002[0475:WITWAM]2.0.CO;2

McRoberts, R.E., Chen, Q., Walters, B.F., & Kaisershot, D.J. (2018). The effects of global positioning system receiver accuracy on airborne laser scanning-assisted estimates of aboveground biomass. Remote Sensing of Environment, 207, 42–49. https://doi.org/10.1016/j.rse.2017.10.062

Pascual, A., Guerra-Hernández, J., Cosenza, D.N., & Sandoval, V. (2020). The role of improved ground positioning and forest structural complexity when performing forest inventory using airborne laser scanning. Remote Sensing, 12(3), 413. https://doi.org/10.3390/rs12030413